const nav=document.getElementById('nav');window.addEventListener('scroll',()=>{nav.classList.toggle('scrolled',window.scrollY>60)});const i18n={currentLang:localStorage.getItem('lang')||'de',supportedLangs:['de','en','fr','it'],translations:{},async init(){for(const lang of this.supportedLangs){try{const response=await fetch(`./translations/${lang}.json`);this.translations[lang]=await response.json()}catch(error){console.error(`Failed to load translation for ${lang}:`,error)}}
this.setLanguage(this.currentLang);this.setupLanguageSelector()},setLanguage(lang){if(!this.supportedLangs.includes(lang))lang='de';this.currentLang=lang;localStorage.setItem('lang',lang);document.documentElement.lang=lang;this.updatePageContent();renderSafetyStatement();applyLanguageBlocks();if(typeof cookieConsent!=='undefined')cookieConsent.refresh();const langSelect=document.getElementById('lang-selector');if(langSelect){langSelect.value=lang}
const activeTab=document.querySelector('.pkg-tab.active');if(activeTab){const audience=activeTab.dataset.audience;updatePackageContent(audience)}},updatePageContent(){const elements=document.querySelectorAll('[data-i18n]');elements.forEach((el)=>{const keys=el.dataset.i18n.split('.');const text=this.getText(...keys);if(el.tagName==='INPUT'||el.tagName==='TEXTAREA'){if(el.placeholder)el.placeholder=text;if(el.dataset.i18nValue==='true')el.value=text}else if(el.dataset.i18nHtml==='true'){el.innerHTML=text}else{el.textContent=text}});this.updateSelectOptions()},getText(section,key){const keys=[section,key];let text=this.translations[this.currentLang];for(const k of keys){text=text?text[k]:null}
return text||`[${section}.${key}]`},updateSelectOptions(){const selects=document.querySelectorAll('[data-i18n-options]');selects.forEach((select)=>{const options=select.dataset.i18nOptions.split(',');const optionsArray=options.map((opt)=>{const[section,key]=opt.trim().split('.');return this.getText(section,key)});Array.from(select.options).forEach((option,index)=>{if(index>0&&index<=optionsArray.length){option.textContent=optionsArray[index-1]}})})},setupLanguageSelector(){const langSelect=document.getElementById('lang-selector');if(langSelect){langSelect.addEventListener('change',(e)=>{const lang=e.target.value;this.setLanguage(lang)})}},t(section,key){return this.getText(section,key)},};function handleSubmit(event){event.preventDefault();const name=document.getElementById('n').value;const email=document.getElementById('e').value;const interest=document.getElementById('i').value;const message=document.getElementById('m').value;if(!name||!email||!message){alert('Bitte füllen Sie alle Felder aus');return}
const formData={name,email,interest:interest||'Keine Angabe',message,language:i18n.currentLang,timestamp:new Date().toISOString(),};console.log('Form submitted:',formData);alert(`Danke! Ihre Nachricht wurde versendet.\n\nWir melden uns innerhalb von 24 Stunden.`);event.target.reset()}
function setupMobileMenu(){const hamburger=document.getElementById('hamburger');const drawer=document.getElementById('drawer');if(!hamburger||!drawer)return;hamburger.addEventListener('click',()=>{const open=hamburger.classList.toggle('open');drawer.classList.toggle('open',open);document.body.style.overflow=open?'hidden':''});document.querySelectorAll('.drawer-link').forEach(link=>{link.addEventListener('click',()=>{hamburger.classList.remove('open');drawer.classList.remove('open');document.body.style.overflow=''})})}
function setupScrollAnimations(){const reveals=document.querySelectorAll('.reveal');const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.style.opacity='1';entry.target.style.transform='translateY(0)'}})});reveals.forEach((el)=>{el.style.opacity='0';el.style.transform='translateY(20px)';el.style.transition='opacity 0.6s ease, transform 0.6s ease';observer.observe(el)})}
function setupPackageTabs(){const tabs=document.querySelectorAll('.pkg-tab');tabs.forEach((tab)=>{tab.addEventListener('click',()=>{const audience=tab.dataset.audience;tabs.forEach((t)=>t.classList.remove('active'));tab.classList.add('active');updatePackageContent(audience)})})}
function updatePackageContent(audience){const titleEl=document.querySelector('.pkg-title');if(titleEl){const titleKey=`h2_${audience}`;const translatedTitle=i18n.getText('packages',titleKey);titleEl.innerHTML=translatedTitle;titleEl.classList.remove('senioren','mieter','ferienhaus');if(audience!=='basis'){titleEl.classList.add(audience)}}
const pkgFeatured=document.querySelector('.pkg-featured');if(pkgFeatured){pkgFeatured.classList.remove('senioren','mieter','ferienhaus');if(audience!=='basis'){pkgFeatured.classList.add(audience)}}
const pkgPremium=document.querySelector('.pkg-premium');if(pkgPremium){pkgPremium.classList.remove('senioren','mieter','ferienhaus');if(audience!=='basis'){pkgPremium.classList.add(audience)}}
const includesEls=document.querySelectorAll('.pkg__includes');if(includesEls.length>0){const includesKey=`pkg_includes_${audience}`;const translatedIncludes=i18n.getText('packages',includesKey);includesEls.forEach((el)=>{el.textContent=translatedIncludes})}
const packages=document.querySelectorAll('.pkg');packages.forEach((card,index)=>{const pkgNumber=index+1;const nameEl=card.querySelector('.pkg__name');if(nameEl){const nameKey=`pkg${pkgNumber}_name_${audience}`;const translatedName=i18n.getText('packages',nameKey);nameEl.textContent=translatedName}
const tagEl=card.querySelector('.pkg__tag');if(tagEl){const tagKey=`pkg${pkgNumber}_tag_${audience}`;const translatedTag=i18n.getText('packages',tagKey);tagEl.textContent=translatedTag}
const outcomeList=card.querySelector('.pkg__outcomes');if(outcomeList)renderFeatureList(outcomeList,pkgNumber,audience,'outcomes');const featureList=card.querySelector('.pkg__list');if(featureList)renderFeatureList(featureList,pkgNumber,audience,'features');});updatePackageSafetyLine(audience)}
function renderFeatureList(listEl,pkgNumber,audience,suffix='features'){const key=`${audience}_pkg${pkgNumber}_${suffix}`;const packages=i18n.translations[i18n.currentLang]?.packages;const items=packages?.[key];if(!Array.isArray(items)){console.warn(`Missing feature list "${key}" for language "${i18n.currentLang}"`);listEl.replaceChildren();return}
listEl.replaceChildren(...items.map((text)=>{const li=document.createElement('li');const check=document.createElement('span');check.className='chk';check.setAttribute('aria-hidden','true');check.textContent='✓';const label=document.createElement('span');label.textContent=text;li.append(check,label);return li}))}
function updatePackageSafetyLine(audience){const line=document.getElementById('pkg-safety-line');if(!line)return;const audiences=(line.dataset.audiences||'').split(/\s+/).filter(Boolean);line.hidden=!audiences.includes(audience)}
function applyLanguageBlocks(){const titleKey=document.body&&document.body.dataset.titleKey;if(titleKey){const[section,key]=titleKey.split('.');document.title=i18n.getText(section,key)+' \u2014 Konihaus'}
document.querySelectorAll('[data-legal-doc]').forEach((doc)=>{const blocks=Array.from(doc.querySelectorAll(':scope > [data-lang]'));if(!blocks.length)return;const fallbackLang=doc.dataset.fallback||'de';const wanted=blocks.find((b)=>b.dataset.lang===i18n.currentLang);const shown=wanted||blocks.find((b)=>b.dataset.lang===fallbackLang)||blocks[0];blocks.forEach((b)=>{b.hidden=b!==shown});const notice=doc.querySelector('.legal__notice');if(notice)notice.hidden=!!wanted})}
function renderSafetyStatement(){const list=document.getElementById('safety-list');if(!list)return;const items=i18n.translations[i18n.currentLang]?.contact?.safety_items;list.replaceChildren(...(Array.isArray(items)?items:[]).map((text)=>{const li=document.createElement('li');li.textContent=text;return li}))}
function setupPackageAccordion(){document.querySelectorAll('.pkg__toggle').forEach((toggle)=>{toggle.addEventListener('click',(e)=>{e.preventDefault();const panel=document.getElementById(toggle.getAttribute('aria-controls'));if(!panel)return;const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));panel.hidden=!open;const pkg=toggle.closest('.pkg');if(pkg)pkg.classList.toggle('expanded',open);})})}
function setupHeroTaglines(){const hero=document.querySelector('.hero');const container=hero&&hero.querySelector('.hero__headline_container');if(!container)return;const TAGLINES=[{bg:'var(--forest-deep)',class:'',keyPrefix:'hero_tagline1'},{bg:'var(--marine)',class:'hero-marine',keyPrefix:'hero_tagline2'},{bg:'var(--gold)',class:'hero-gold',keyPrefix:'hero_tagline3'},{bg:'var(--burgundy)',class:'hero-burgundy',keyPrefix:'hero_tagline4'},];const HOLD_MS=5000;const OUT_MS=450;const IN_MS=550;const canAnimate=typeof hero.animate==='function';const reduceMotion=window.matchMedia?window.matchMedia('(prefers-reduced-motion: reduce)'):{matches:!1};let index=0;let current=container.querySelector('.hero__h1');let pending=null;let timer=null;function removeStrays(){container.querySelectorAll('.hero__h1').forEach((h)=>{if(h!==current&&!(pending&&h===pending.incoming))h.remove();})}
function applyTheme(tagline){hero.style.backgroundColor=tagline.bg;hero.classList.remove('hero-marine','hero-gold','hero-burgundy');if(tagline.class)hero.classList.add(tagline.class);}
function createHeadline(tagline){const h1=document.createElement('h1');h1.className='hero__h1';h1.setAttribute('data-i18n',`hero.${tagline.keyPrefix}`);h1.setAttribute('data-i18n-html','true');h1.innerHTML=i18n.getText('hero',tagline.keyPrefix);h1.style.animation='none';return h1}
function settle(){if(!pending)return;const{outgoing,incoming,animations}=pending;pending=null;animations.forEach((a)=>a.cancel());outgoing.remove();incoming.style.opacity='';current=incoming;removeStrays();schedule()}
function schedule(){clearTimeout(timer);timer=null;if(!document.hidden&&!pending)timer=setTimeout(rotate,HOLD_MS);}
function rotate(){timer=null;if(document.hidden||pending)return;if(!current||!container.contains(current))current=container.querySelector('.hero__h1');removeStrays();index=(index+1)%TAGLINES.length;const tagline=TAGLINES[index];const outgoing=current;const incoming=createHeadline(tagline);incoming.style.opacity='0';container.appendChild(incoming);applyTheme(tagline);if(!outgoing){incoming.style.opacity='';current=incoming;schedule();return}
if(!canAnimate||reduceMotion.matches){pending={outgoing,incoming,animations:[]};settle();return}
const out=outgoing.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-50px)'}],{duration:OUT_MS,easing:'ease-in',fill:'forwards'});const into=incoming.animate([{opacity:0,transform:'translateY(50px)'},{opacity:1,transform:'translateY(0)'}],{duration:IN_MS,delay:OUT_MS,easing:'ease-out',fill:'both'});const mine={outgoing,incoming,animations:[out,into]};pending=mine;Promise.all([out.finished,into.finished]).then(()=>{if(pending===mine)settle();}).catch(()=>{})}
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(timer);timer=null}else{settle();removeStrays();schedule()}});schedule()}
document.addEventListener('DOMContentLoaded',()=>{i18n.init().then(()=>{if(typeof cookieConsent!=='undefined')cookieConsent.init();setupMobileMenu();setupScrollAnimations();setupPackageTabs();setupPackageAccordion();setupHeroTaglines();updatePackageContent('basis');const moreStart=document.getElementById('morestart');if(moreStart){moreStart.addEventListener('click',(e)=>{e.preventDefault();document.getElementById('trustsection').scrollIntoView()})}})});if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('/sw.js').then((registration)=>{console.log('Service Worker registered successfully:',registration);setInterval(()=>{registration.update()},60000)}).catch((error)=>{console.warn('Service Worker registration failed:',error)})});navigator.serviceWorker.addEventListener('controllerchange',()=>{console.log('Service Worker updated')})}